version: "1.0"
services:
  mongo: 
    image: mongo
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    container_name: backend_c
    ports:
      - "5000:5000"
    depends_on: 
      - mongo
    volumes:
      - ./backend:/app #local directory:/dockerfile workdir 
      - /app/node_modules #dont want to copy
    environment:
      - MONGO_URL=mongodb+srv://admin:N06Wmrc08@mern-hotel-mgr-db.izrwlar.mongodb.net/?retryWrites=true&w=majority&appName=mern-hotel-mgr-db
  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - "5173:5173"
    depends_on: 
      - backend
    volumes:
      - ./frontend:/app #local directory:/dockerfile workdir 
      - /app/node_modules #dont want to copy
volumes:
  mongo-data:
  